[build]
  command = "node build-config.js"
  publish = "."   # or "public" / "dist" depending on your main site structure

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "GOOGLE_CLIENT_ID"

[[redirects]]
  from = "/pointz/*"
  to = "/pointz/index.html"
  status = 200